"""Add content_type and difficulty_level to topics

Revision ID: d1ff986621a5
Revises: 009
Create Date: 2026-09-22 14:59:15.883294+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1ff986621a5'
down_revision: Union[str, Sequence[str], None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_experiments', 'traffic_split',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ab_experiments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_ab_experiments_name'), table_name='ab_experiments')
    op.create_index(op.f('ix_ab_experiments_name'), 'ab_experiments', ['name'], unique=True)
    op.alter_column('artifact_versions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('artifacts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('artifacts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('block_embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_block_embeddings_hnsw'), table_name='block_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('book_ingestion_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'lang_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_books_natural_key', 'books', ['natural_key'])
    op.alter_column('chapters', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_chapters_natural_key', 'chapters', ['natural_key'])
    op.alter_column('content_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_blocks', 'block_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_content_blocks_fts'), table_name='content_blocks', postgresql_using='gin')
    op.drop_index(op.f('idx_content_blocks_hash'), table_name='content_blocks')
    op.drop_index(op.f('idx_content_blocks_keywords_gin'), table_name='content_blocks', postgresql_using='gin')
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'topics_covered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_conversations_bloom_gin'), table_name='conversations', postgresql_using='gin')
    op.drop_index(op.f('idx_conversations_user_pinned'), table_name='conversations', postgresql_where='((is_pinned = true) AND (is_deleted = false))')
    op.drop_index(op.f('idx_conversations_user_updated'), table_name='conversations', postgresql_where='(is_deleted = false)')
    op.alter_column('job_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_queue', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_job_queue_next'), table_name='job_queue', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('learning_preferences', 'prefers_examples',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_analogies',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_step_by_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_visuals',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'preferred_length',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'attention_span',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('learning_preferences', 'responds_to_encouragement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'prompt_template',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('llm_call_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_llm_logs_date_user'), table_name='llm_call_logs')
    op.alter_column('message_content_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('message_content_blocks', 'block_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_msg_content_blocks_fts'), table_name='message_content_blocks', postgresql_using='gin')
    op.alter_column('message_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('message_sources', 'used_in_answer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'is_active_branch',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_conv_created'), table_name='messages', postgresql_where='(is_active_branch = true)')
    op.alter_column('overall_cognitive_profiles', 'concept_master_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'error_repetition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'attempt_persistence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'struggle_recovery_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'practice_intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'learning_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'knowledge_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'cognitive_thinking_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'engagement_frequency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'assessment_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_pending_signals_gin'), table_name='pending_metric_signals', postgresql_using='gin')
    op.alter_column('prompt_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('prompt_templates', 'slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('prompt_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'num_questions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_quiz_attempts_user_created'), table_name='quiz_attempts')
    op.alter_column('session_insights', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_insights', 'topics_mastered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('session_insights', 'topics_struggled',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('session_insights', 'misconceptions_found',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('session_insights', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('share_links', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_goals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_goals', 'current_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_memory_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_memory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_memory_items_user_active'), table_name='student_memory_items', postgresql_where='(is_active = true)')
    op.alter_column('student_profiles', 'preferred_lang',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'current_streak_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'longest_streak_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_active_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_questions_asked',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_quizzes_taken',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'concept_master_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'error_repetition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'attempt_persistence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'struggle_recovery_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'practice_intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'learning_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'knowledge_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'cognitive_thinking_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'engagement_frequency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'assessment_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'bloom_level_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'frustration_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'confidence_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'total_chat_turns',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'total_quizzes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'avg_session_duration_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_tasks', 'is_done',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('study_spaces', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('study_spaces', 'pinned_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('study_spaces', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_questions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_correct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'avg_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'mcq_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'theory_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'weak_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subject_quiz_feedback', 'strong_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subjects', 'lang_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subtopics', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'mastery_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'bloom_level_reached',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'times_visited',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'understood_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('topic_mastery', 'confused_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('topic_mastery', 'common_mistakes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('topic_mastery', 'review_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'decay_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topic_mastery', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_topic_mastery_review_compound'), table_name='topic_mastery', postgresql_where='(next_review_date IS NOT NULL)')
    op.add_column('topics', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('topics', sa.Column('difficulty_level', sa.String(length=50), nullable=True))
    op.alter_column('topics', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_topics_natural_key', 'topics', ['natural_key'])
    op.alter_column('usage_ledger', 'messages_sent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_ledger', 'tokens_input',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_ledger', 'tokens_output',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_ledger', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'student'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('usage_ledger', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('usage_ledger', 'tokens_output',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usage_ledger', 'tokens_input',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usage_ledger', 'messages_sent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint('uq_topics_natural_key', 'topics', type_='unique')
    op.alter_column('topics', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('topics', 'difficulty_level')
    op.drop_column('topics', 'content_type')
    op.create_index(op.f('idx_topic_mastery_review_compound'), 'topic_mastery', ['user_id', 'next_review_date', 'mastery_level'], unique=False, postgresql_where='(next_review_date IS NOT NULL)')
    op.alter_column('topic_mastery', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('topic_mastery', 'decay_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('topic_mastery', 'review_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('topic_mastery', 'common_mistakes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('topic_mastery', 'confused_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('topic_mastery', 'understood_concepts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('topic_mastery', 'times_visited',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('topic_mastery', 'bloom_level_reached',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('topic_mastery', 'mastery_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('subtopics', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subjects', 'lang_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'strong_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('subject_quiz_feedback', 'weak_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('subject_quiz_feedback', 'theory_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'mcq_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'avg_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_correct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_questions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'total_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subject_quiz_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('study_spaces', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('study_spaces', 'pinned_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('study_spaces', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('student_tasks', 'is_done',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'avg_session_duration_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'total_quizzes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'total_chat_turns',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'confidence_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'frustration_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'bloom_level_avg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'assessment_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'engagement_frequency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'cognitive_thinking_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'knowledge_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'learning_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'practice_intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'struggle_recovery_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'attempt_persistence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'error_repetition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'concept_master_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('student_subject_profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_quizzes_taken',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_questions_asked',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'total_active_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'longest_streak_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_streaks', 'current_streak_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_profiles', 'preferred_lang',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_memory_items_user_active'), 'student_memory_items', ['user_id', 'subject_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('student_memory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('student_memory_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('student_goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('student_goals', 'current_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('student_goals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('share_links', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('session_insights', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('session_insights', 'misconceptions_found',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('session_insights', 'topics_struggled',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('session_insights', 'topics_mastered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('session_insights', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_quiz_attempts_user_created'), 'quiz_attempts', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('quiz_attempts', 'num_questions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('7'),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index(op.f('idx_pending_signals_gin'), 'pending_metric_signals', ['signals'], unique=False, postgresql_using='gin')
    op.alter_column('overall_cognitive_profiles', 'assessment_accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'engagement_frequency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'cognitive_thinking_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'knowledge_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'learning_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'practice_intensity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'struggle_recovery_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'attempt_persistence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'error_repetition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('overall_cognitive_profiles', 'concept_master_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.create_index(op.f('idx_messages_conv_created'), 'messages', ['conversation_id', 'created_at'], unique=False, postgresql_where='(is_active_branch = true)')
    op.alter_column('messages', 'is_active_branch',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('message_sources', 'used_in_answer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('message_feedback', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_msg_content_blocks_fts'), 'message_content_blocks', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(content, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('message_content_blocks', 'block_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('message_content_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_llm_logs_date_user'), 'llm_call_logs', [sa.literal_column('created_at DESC'), 'user_id'], unique=False)
    op.alter_column('llm_call_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_call_logs', 'prompt_template',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'ad_hoc'::character varying"),
               existing_nullable=True)
    op.alter_column('learning_preferences', 'responds_to_encouragement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'attention_span',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'50'::double precision"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'preferred_length',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_visuals',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_step_by_step',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_analogies',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('learning_preferences', 'prefers_examples',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.create_index(op.f('idx_job_queue_next'), 'job_queue', ['priority', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('job_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('job_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('job_queue', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('job_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_conversations_user_updated'), 'conversations', ['user_id', sa.literal_column('updated_at DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_conversations_user_pinned'), 'conversations', ['user_id', 'is_pinned'], unique=False, postgresql_where='((is_pinned = true) AND (is_deleted = false))')
    op.create_index(op.f('idx_conversations_bloom_gin'), 'conversations', ['bloom_levels_hit'], unique=False, postgresql_using='gin')
    op.alter_column('conversations', 'topics_covered',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('conversations', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_content_blocks_keywords_gin'), 'content_blocks', ['enriched_keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_content_blocks_hash'), 'content_blocks', ['content_hash'], unique=False)
    op.create_index(op.f('idx_content_blocks_fts'), 'content_blocks', [sa.literal_column("to_tsvector('english'::regconfig, raw_text)")], unique=False, postgresql_using='gin')
    op.alter_column('content_blocks', 'block_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('content_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.drop_constraint('uq_chapters_natural_key', 'chapters', type_='unique')
    op.alter_column('chapters', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint('uq_books_natural_key', 'books', type_='unique')
    op.alter_column('books', 'lang_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('book_ingestion_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_block_embeddings_hnsw'), 'block_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('block_embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'text-embedding-3-small-1536'::character varying"),
               existing_nullable=False)
    op.alter_column('artifacts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('artifacts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('artifact_versions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ab_experiments_name'), table_name='ab_experiments')
    op.create_index(op.f('idx_ab_experiments_name'), 'ab_experiments', ['name'], unique=True)
    op.alter_column('ab_experiments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('ab_experiments', 'traffic_split',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               existing_nullable=False)
    # ### end Alembic commands ###
