from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.sql import func

Base = declarative_base()

class Board(Base):
    __tablename__ = "boards"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    description = Column(Text, nullable=True)
    
    classes = relationship("SchoolClass", back_populates="board", cascade="all, delete-orphan")

class SchoolClass(Base):
    __tablename__ = "classes"
    id = Column(Integer, primary_key=True, index=True)
    board_id = Column(Integer, ForeignKey("boards.id"), nullable=False)
    name = Column(String(50), nullable=False)
    level = Column(Integer, nullable=False)  # e.g., 7 for Class 7
    
    board = relationship("Board", back_populates="classes")
    subjects = relationship("Subject", back_populates="school_class", cascade="all, delete-orphan")

class Subject(Base):
    __tablename__ = "subjects"
    id = Column(Integer, primary_key=True, index=True)
    class_id = Column(Integer, ForeignKey("classes.id"), nullable=False)
    name = Column(String(100), nullable=False)
    
    school_class = relationship("SchoolClass", back_populates="subjects")
    chapters = relationship("Chapter", back_populates="subject", cascade="all, delete-orphan")

class Chapter(Base):
    __tablename__ = "chapters"
    id = Column(Integer, primary_key=True, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=False)
    title = Column(String(200), nullable=False)
    chapter_number = Column(Integer, nullable=False)
    summary = Column(Text, nullable=True) # Generated by LLM
    
    subject = relationship("Subject", back_populates="chapters")
    topics = relationship("Topic", back_populates="chapter", cascade="all, delete-orphan")

class Topic(Base):
    __tablename__ = "topics"
    id = Column(Integer, primary_key=True, index=True)
    chapter_id = Column(Integer, ForeignKey("chapters.id"), nullable=False)
    title = Column(String(200), nullable=False)
    topic_number = Column(String(50), nullable=True) # e.g. "1.1"
    summary = Column(Text, nullable=True) # Generated by LLM
    
    chapter = relationship("Chapter", back_populates="topics")
    chunks = relationship("ContentChunk", back_populates="topic", cascade="all, delete-orphan")

class ContentChunk(Base):
    __tablename__ = "content_chunks"
    id = Column(Integer, primary_key=True, index=True)
    topic_id = Column(Integer, ForeignKey("topics.id"), nullable=False)
    content = Column(Text, nullable=False)
    chunk_index = Column(Integer, nullable=False) # Order within topic
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    topic = relationship("Topic", back_populates="chunks")


# ─────────────────────────────────────────────────────────────────────────────
# Conversation Memory
# ─────────────────────────────────────────────────────────────────────────────

class ConversationSession(Base):
    """
    Groups a series of student ↔ tutor exchanges into one conversation.
    A session is created when the student starts chatting and persists
    across multiple turns until they start a new one.
    """
    __tablename__ = "conversation_sessions"
    id = Column(String(100), primary_key=True)              # UUID session_id
    class_num = Column(Integer, nullable=True)
    subject = Column(String(100), nullable=True)
    summary = Column(Text, nullable=True)                   # compressed memory of older turns
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    messages = relationship(
        "ConversationMessage",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="ConversationMessage.created_at",
    )


class ConversationMessage(Base):
    """
    A single message in a conversation — either from the student or the tutor.
    Stores the context and routing metadata for debugging / audit.
    """
    __tablename__ = "conversation_messages"
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(100), ForeignKey("conversation_sessions.id"), nullable=False)
    role = Column(String(20), nullable=False)                # "student" or "tutor"
    content = Column(Text, nullable=False)
    context_used = Column(Text, nullable=True)               # retrieved context (for audit)
    routed_topic = Column(String(200), nullable=True)        # which topic was matched
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    session = relationship("ConversationSession", back_populates="messages")
