"""
app/data/models/chat.py
────────────────────────
Chat domain ORM models: conversations, message tree, sources, artifacts.

Design decisions:
  - Conversation has NO content — it's a container for messages.
  - Message has NO text — content lives in MessageContentBlock (typed blocks).
    This supports: text, code, image, citation, artifact_ref, tool_use, tool_result.
  - parent_message_id + is_active_branch implement the conversation tree
    (supports edit/regenerate branching — deferred from frontend, see addons.md).
  - MessageSource: links each assistant message to specific content blocks
    with rank and score. This is the citation table.
  - Artifact + ArtifactVersion: versioned generated notes/flashcards stored as JSONB.
  - ShareLink: frozen conversation snapshot for read-only sharing.
  - ToolCallLog: audit trail for every tool use (calculator, quiz gen, retrieval).
"""
import uuid
from sqlalchemy import (
    Column, String, Integer, Boolean, DateTime, Text, Float,
    ForeignKey, UniqueConstraint, Index, CheckConstraint, SmallInteger,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.data.models.base import Base, register_updated_at_listener


class Conversation(Base):
    """
    A conversation between a student and the AI.

    subject_id: optional — set when conversation is tied to a specific subject.
    study_space_id: optional — groups conversation under a Study Space.
    active_message_id: points to the leaf message of the currently active branch.
    title: auto-generated by LLM after the first turn; editable by student.
    is_pinned / is_archived / is_deleted: soft-state flags.
    """
    __tablename__ = "conversations"
    __table_args__ = (
        Index("idx_conversations_user_id", "user_id"),
        Index("idx_conversations_subject_id", "subject_id"),
        Index("idx_conversations_created_at", "created_at"),
    )

    id               = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id          = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    subject_id       = Column(Integer, ForeignKey("subjects.id", ondelete="SET NULL"), nullable=True)
    study_space_id   = Column(UUID(as_uuid=True), ForeignKey("study_spaces.id", ondelete="SET NULL"), nullable=True)
    title            = Column(String(200), nullable=True)        # LLM-generated, user-editable
    active_message_id = Column(UUID(as_uuid=True), nullable=True)  # no FK to avoid circular; validated in service
    is_pinned        = Column(Boolean, nullable=False, default=False)
    is_archived      = Column(Boolean, nullable=False, default=False)
    is_deleted       = Column(Boolean, nullable=False, default=False)
    # Analytics
    total_messages       = Column(Integer, nullable=False, default=0)
    session_mood         = Column(String(30), nullable=True)    # positive | neutral | frustrated | confused
    bloom_levels_hit     = Column(JSONB, nullable=True)         # {"remember": 3, "understand": 1, ...}
    topics_covered       = Column(JSONB, nullable=False, default=list)  # [topic_id, ...]
    last_topic_name      = Column(String(300), nullable=True)
    memory_summary       = Column(Text, nullable=True)          # Rolling conversation summary for context
    ended_at             = Column(DateTime(timezone=True), nullable=True)
    session_duration_sec = Column(Integer, nullable=True)
    created_at           = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at           = Column(DateTime(timezone=True), nullable=True, onupdate=func.now())

    user        = relationship("User", back_populates="conversations")
    subject     = relationship("Subject")
    study_space = relationship("StudySpace", back_populates="conversations")
    messages    = relationship("Message", back_populates="conversation", cascade="all, delete-orphan",
                               foreign_keys="Message.conversation_id")
    insights    = relationship("SessionInsight", back_populates="conversation", cascade="all, delete-orphan")
    quiz_attempts = relationship("QuizAttempt", back_populates="conversation")
    share_links = relationship("ShareLink", back_populates="conversation", cascade="all, delete-orphan")
    artifacts   = relationship("Artifact", back_populates="conversation")
    diagnostic  = relationship("DiagnosticState", back_populates="conversation", uselist=False,
                               cascade="all, delete-orphan")


register_updated_at_listener(Conversation)


class Message(Base):
    """
    A single message node in the conversation tree.

    role: 'student' | 'assistant' | 'system'
    parent_message_id: NULL for the root message; points to parent node.
    is_active_branch: True for the currently visible sibling (one True per sibling group).

    Content is NOT stored here — see MessageContentBlock.
    This separation supports typed multi-block messages (text + code + citation, etc.)
    """
    __tablename__ = "messages"
    __table_args__ = (
        CheckConstraint("role IN ('student', 'assistant', 'system')", name="ck_messages_role"),
        Index("idx_messages_conversation_id", "conversation_id"),
        Index("idx_messages_parent_id", "parent_message_id"),
        Index("idx_messages_created_at", "created_at"),
    )

    id                = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    conversation_id   = Column(UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False)
    parent_message_id = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=True)
    role              = Column(String(20), nullable=False)    # student | assistant | system
    is_active_branch  = Column(Boolean, nullable=False, default=True)
    idempotency_key   = Column(String(64), nullable=True, unique=True)  # client-supplied dedup key
    # Per-message analytics
    response_time_ms  = Column(Integer, nullable=True)
    token_count       = Column(Integer, nullable=True)
    sentiment         = Column(String(20), nullable=True)    # positive | neutral | negative | confused | frustrated
    bloom_level       = Column(String(30), nullable=True)    # remember | understand | apply | analyze | evaluate | create
    contains_question = Column(Boolean, nullable=True)
    topic_id          = Column(Integer, ForeignKey("topics.id", ondelete="SET NULL"), nullable=True)
    created_at        = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    conversation  = relationship("Conversation", back_populates="messages", foreign_keys=[conversation_id])
    parent        = relationship("Message", remote_side="Message.id", back_populates="children", foreign_keys=[parent_message_id])
    children      = relationship("Message", back_populates="parent", foreign_keys=[parent_message_id])
    content_blocks = relationship("MessageContentBlock", back_populates="message",
                                  cascade="all, delete-orphan", order_by="MessageContentBlock.block_index")
    sources       = relationship("MessageSource", back_populates="message", cascade="all, delete-orphan")
    feedback      = relationship("MessageFeedback", back_populates="message", cascade="all, delete-orphan")
    tool_calls    = relationship("ToolCallLog", back_populates="message", cascade="all, delete-orphan")
    topic         = relationship("Topic")


class MessageContentBlock(Base):
    """
    A typed content block within a message.

    block_type:
      'text'         — plain markdown text
      'code'         — code block with language metadata
      'image'        — image URL or base64 (for attachments)
      'citation'     — reference to a content_block (textbook citation)
      'artifact_ref' — reference to an Artifact
      'tool_use'     — tool call request (function call)
      'tool_result'  — tool call result

    content: the main text / markdown content
    metadata: JSONB for type-specific extras:
      code → {"language": "python"}
      citation → {"block_id": 123, "chapter": "...", "topic": "..."}
      artifact_ref → {"artifact_id": "uuid"}
      tool_use → {"tool_name": "...", "args": {...}}
      tool_result → {"tool_call_id": "...", "result": {...}}
    """
    __tablename__ = "message_content_blocks"
    __table_args__ = (
        UniqueConstraint("message_id", "block_index", name="uq_msg_blocks_msg_index"),
        CheckConstraint(
            "block_type IN ('text','code','image','citation','artifact_ref','tool_use','tool_result')",
            name="ck_msg_block_type",
        ),
        Index("idx_msg_content_blocks_message_id", "message_id"),
    )

    id          = Column(Integer, primary_key=True, autoincrement=True)
    message_id  = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False)
    block_type  = Column(String(20), nullable=False, default="text")
    content     = Column(Text, nullable=True)
    extra_data  = Column("metadata", JSONB, nullable=True)   # 'metadata' is reserved in SA; column name stays 'metadata' in DB
    block_index = Column(Integer, nullable=False, default=0)

    message = relationship("Message", back_populates="content_blocks")


class MessageSource(Base):
    """
    Links an assistant message to the content blocks it was grounded in.
    One row per (message, block) pair.

    rank: retrieval rank (1 = highest scored).
    score: cosine similarity score from pgvector.
    used_in_answer: True if this block's text was injected into the LLM prompt.
    """
    __tablename__ = "message_sources"
    __table_args__ = (
        UniqueConstraint("message_id", "block_id", name="uq_msg_sources_msg_block"),
        Index("idx_msg_sources_message_id", "message_id"),
        Index("idx_msg_sources_block_id", "block_id"),
        CheckConstraint("score BETWEEN 0.0 AND 1.0", name="ck_msg_sources_score"),
    )

    id             = Column(Integer, primary_key=True, autoincrement=True)
    message_id     = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False)
    block_id       = Column(Integer, ForeignKey("content_blocks.id", ondelete="CASCADE"), nullable=False)
    rank           = Column(SmallInteger, nullable=False)
    score          = Column(Float, nullable=False)
    used_in_answer = Column(Boolean, nullable=False, default=True)

    message = relationship("Message", back_populates="sources")
    block   = relationship("ContentBlock", back_populates="sources")


class Artifact(Base):
    """
    AI-generated learning artifact (notes, flashcards, mindmap, practice set).
    Versioned: actual content is in ArtifactVersion.

    artifact_type: 'notes' | 'flashcards' | 'mindmap' | 'practice_set'
    current_version_id: points to the active version (updated on each edit).
    """
    __tablename__ = "artifacts"
    __table_args__ = (
        CheckConstraint(
            "artifact_type IN ('notes','flashcards','mindmap','practice_set')",
            name="ck_artifact_type",
        ),
        Index("idx_artifacts_user_id", "user_id"),
    )

    id                 = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id            = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    conversation_id    = Column(UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="SET NULL"), nullable=True)
    artifact_type      = Column(String(30), nullable=False)
    title              = Column(String(200), nullable=False)
    current_version_id = Column(UUID(as_uuid=True), nullable=True)  # updated after each save
    is_deleted         = Column(Boolean, nullable=False, default=False)
    created_at         = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at         = Column(DateTime(timezone=True), nullable=True, onupdate=func.now())

    user         = relationship("User")
    conversation = relationship("Conversation", back_populates="artifacts")
    versions     = relationship("ArtifactVersion", back_populates="artifact", cascade="all, delete-orphan")


register_updated_at_listener(Artifact)


class ArtifactVersion(Base):
    """
    One immutable version of an Artifact's content.
    content JSONB schema depends on artifact_type:
      notes:        {"markdown": "..."}
      flashcards:   {"cards": [{"front": "...", "back": "..."}]}
      mindmap:      {"nodes": [...], "edges": [...]}
      practice_set: {"questions": [...]}  (same shape as quiz_questions)
    """
    __tablename__ = "artifact_versions"
    __table_args__ = (
        UniqueConstraint("artifact_id", "version_num", name="uq_artifact_versions"),
        Index("idx_artifact_versions_artifact_id", "artifact_id"),
    )

    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    artifact_id = Column(UUID(as_uuid=True), ForeignKey("artifacts.id", ondelete="CASCADE"), nullable=False)
    version_num = Column(Integer, nullable=False)
    content     = Column(JSONB, nullable=False)
    created_at  = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    artifact = relationship("Artifact", back_populates="versions")


class ShareLink(Base):
    """
    Read-only revocable share link to a conversation snapshot.
    token: random 32-byte hex string, stored plaintext (it's not a secret credential).
    snapshot: JSONB frozen copy of messages at share time.
    """
    __tablename__ = "share_links"
    __table_args__ = (
        Index("idx_share_links_conversation_id", "conversation_id"),
        Index("idx_share_links_token", "token"),
    )

    id              = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    conversation_id = Column(UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False)
    user_id         = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    token           = Column(String(64), nullable=False, unique=True)
    snapshot        = Column(JSONB, nullable=True)
    expires_at      = Column(DateTime(timezone=True), nullable=True)
    revoked_at      = Column(DateTime(timezone=True), nullable=True)
    created_at      = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    conversation = relationship("Conversation", back_populates="share_links")
    user         = relationship("User")


class MessageFeedback(Base):
    """
    Student feedback on a single message (thumbs up/down + optional reason).
    rating: 1 = thumbs up, -1 = thumbs down, 0 = explicit reset.
    """
    __tablename__ = "message_feedback"
    __table_args__ = (
        UniqueConstraint("message_id", "user_id", name="uq_msg_feedback_msg_user"),
        CheckConstraint("rating IN (-1, 0, 1)", name="ck_msg_feedback_rating"),
        Index("idx_msg_feedback_message_id", "message_id"),
    )

    id         = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    message_id = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False)
    user_id    = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    rating     = Column(SmallInteger, nullable=False)
    reason     = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    message = relationship("Message", back_populates="feedback")
    user    = relationship("User")


class ToolCallLog(Base):
    """
    Audit trail for every tool invocation (retrieval, calculator, quiz generator, etc.)
    tool_name: 'textbook_retrieval' | 'quiz_generator' | 'flashcard_generator' | 'calculator'
    input / output: full JSONB payloads.
    error: filled in if the tool call failed.
    """
    __tablename__ = "tool_call_log"
    __table_args__ = (
        Index("idx_tool_call_log_message_id", "message_id"),
    )

    id          = Column(Integer, primary_key=True, autoincrement=True)
    message_id  = Column(UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False)
    tool_name   = Column(String(100), nullable=False)
    input       = Column(JSONB, nullable=True)
    output      = Column(JSONB, nullable=True)
    error       = Column(Text, nullable=True)
    duration_ms = Column(Integer, nullable=True)
    created_at  = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    message = relationship("Message", back_populates="tool_calls")
